Catch service errors to display standardized error page
georchestra/georchestra-gateway pull request #122
Opened 2024-05-16 07:45 UTC by emmdurin

We wanted to show a standardized error page when a service behind the gateway returns a 500 error, instead of a service-specific error page.

This implementation uses `500.html` template embedded in gateway or overriden in `gateway/template/error` directory of datadir.

To enable it globally, add this to `gateway/application.yaml` of datadir :
`
spring:
  cloud:
    gateway:
      default-filters:
        - ServiceError
`

To enable it only on some routes, add this to concerned routes in `gateway/routes.yaml` of datadir :
`
        filters:
        - name: ServiceError
`

2024-05-16 07:47 UTC, pmauduit commented
poke @groldan I think DT's request is similar to what is intended here.

2024-05-16 14:05 UTC, groldan requested changes

2024-05-16 14:05 UTC, groldan commented on gateway/src/main/java/org/georchestra/gateway/filter/headers/ServiceErrorGatewayFilterFactory.java
> +                    throw new RuntimeException("SERVICE ERROR");
It'd be ideal if we throw an exception that preserves the status code. I can't remember how they're called right now though

2024-05-16 14:05 UTC, groldan commented on gateway/src/main/java/org/georchestra/gateway/filter/headers/ServiceErrorGatewayFilterFactory.java
> +                    throw new RuntimeException("SERVICE ERROR");
`org.springframework.web.server.ResponseStatusException` that's it

2024-05-16 14:07 UTC, groldan requested changes
Also, as discussed in our meeting, it'd be great if this filter could be enabled through a config property, being disabled by default

2024-05-16 14:11 UTC, groldan commented
> Also, as discussed in our meeting, it'd be great if this filter could be enabled through a config property, being disabled by default

either way, whether it's enabled or disabled by default, just make sure to add an entry in the security docs

2024-05-27 20:27 UTC, groldan approved these changes

2024-05-27 20:28 UTC, merged