Adds preauth external provider header
georchestra/georchestra-gateway pull request #131
Opened 2024-06-24 21:23 UTC by f-necas

This allows to use headers : 
```
  --header 'preauth-provider: myprov' \
  --header 'preauth-provider-id: myprovid' \
```
in preauth authentication

2024-06-25 08:05 UTC, pmauduit requested changes
Looks good but it would also require to modify the documentation related to preauthentication, around here:
https://github.com/georchestra/georchestra-gateway/blob/main/docs/pre-authentication.adoc?plain=1#L25-L33 and https://github.com/georchestra/georchestra-gateway/blob/main/docs/pre-authentication.adoc?plain=1#L147-L182

2024-06-25 08:05 UTC, pmauduit commented on gateway/src/main/java/org/georchestra/gateway/security/preauth/PreauthAuthenticationManager.java
> +        user.setOAuth2Uid(providerId);
I'd add a TODO-comment and maybe create an issue on georchestra/georchestra or here, to stress the fact that the oauth2provider / uid field on the user is misnamed and is also used by external (preauthentication) mechanisms.

2024-06-26 07:32 UTC, f-necas commented
Issue created : https://github.com/georchestra/georchestra/issues/4268

2024-06-26 08:50 UTC, pmauduit approved these changes

2024-06-26 09:05 UTC, merged