Fix rabbitmq event sending process after code refactor
georchestra/georchestra-gateway pull request #81
Opened 2023-11-14 23:20 UTC by marwanehcine

fix rabbitmq event sending process after code refactor

2023-12-13 13:44 UTC, pmauduit requested changes
The GHA is failing:
https://github.com/georchestra/georchestra-gateway/pull/81/checks

so I wouldd expect the PR is not ready for review yet

2023-12-13 13:44 UTC, pmauduit commented on gateway/src/test/java/org/georchestra/gateway/rabbitmq/SendMessageRabbitmqIT.java
> +        "georchestra.datadir=${user.dir}/src/test/resources/data_directory" })
It does not sound to me as very portable, it doestn't resolve on my dev environment.

2023-12-13 13:44 UTC, pmauduit commented on gateway/src/test/java/org/georchestra/gateway/rabbitmq/SendMessageRabbitmqIT.java
> +            e.printStackTrace();
I'd make use of a logger, even in a test context.

2023-12-13 19:54 UTC, marwanehcine commented
> The GHA is failing: https://github.com/georchestra/georchestra-gateway/pull/81/checks
> 
> so I wouldd expect the PR is not ready for review yet

This needs this PR to be merged before to make compilation works :
https://github.com/georchestra/georchestra/pull/4098/files

2024-01-17 08:10 UTC, pmauduit commented on gateway/src/test/java/org/georchestra/gateway/rabbitmq/SendMessageRabbitmqIT.java
> +    private static String getLocalIpAddress() {
the method is unused anymore

2024-01-18 09:07 UTC, pmauduit approved these changes

2024-01-18 09:07 UTC, pmauduit commented on gateway/pom.xml
> +    with rabbitmq and smtp containers.-->
maybe the comment is not necessary, I think we can assume that if the dependency is added (especially with a test scope), it's for testing purposes ;-) and the reference to smtp is a bit confusing for this dependency in particular

2024-01-18 09:13 UTC, pmauduit commented
> This needs this PR to be merged before to make compilation works :
> https://github.com/georchestra/georchestra/pull/4098/files

I am still concerned by the failing testsuite though, the above mentioned PR has been closed without being merged, and no traces of a SmtpContainer in the georchestra/georchestra repository yet.

2024-01-19 10:01 UTC, merged